version: "001"
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
networks:
  default:
    name: pg-network
    external: true
    